--
-- PostgreSQL database dump
--

\restrict Cs7LmYAjeD5xKkSjiLOMExHYTyIzL6XuQ5Ie2RbT3vcShFD7j3IgcqGYvQQ712k

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-15 23:07:14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 16454)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 5042 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16456)
-- Name: participantes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.participantes (
    id bigint NOT NULL,
    correo character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.participantes OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16455)
-- Name: participantes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.participantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16465)
-- Name: partidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partidos (
    ronda integer,
    ganador_id bigint,
    id bigint NOT NULL,
    id_del_torneo bigint,
    jugador1_id bigint,
    jugador2_id bigint,
    siguiente_partido_id bigint,
    torneo_id bigint,
    fase character varying(255),
    puntuacion_jugador1 integer,
    puntuacion_jugador2 integer
);


ALTER TABLE public.partidos OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16464)
-- Name: partidos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16471)
-- Name: torneo_participante; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.torneo_participante (
    participante_id bigint NOT NULL,
    torneo_id bigint NOT NULL
);


ALTER TABLE public.torneo_participante OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16477)
-- Name: torneos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.torneos (
    id bigint NOT NULL,
    estado character varying(255),
    juego character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.torneos OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16476)
-- Name: torneos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.torneos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.torneos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5031 (class 0 OID 16456)
-- Dependencies: 220
-- Data for Name: participantes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.participantes (id, correo, nombre) FROM stdin;
1	ryangs@gmail.com	Ryan GS
2	eljefe@gmail.com	El jefe
3	sliverrk@gmail.com	SliverRk
4	mamutland@gmail.com	Kolderiu
5	cesarrk@gmail.com	cesarRK
6	humildefc@gmail.com	Robert PG
7	djmario@gmail.com	DjMaRiiO
8	ibaillanos@gmail.com	Ibai 
\.


--
-- TOC entry 5033 (class 0 OID 16465)
-- Dependencies: 222
-- Data for Name: partidos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partidos (ronda, ganador_id, id, id_del_torneo, jugador1_id, jugador2_id, siguiente_partido_id, torneo_id, fase, puntuacion_jugador1, puntuacion_jugador2) FROM stdin;
\N	1	5	3	1	2	\N	\N	LIGA	312	188
\N	3	6	3	1	3	\N	\N	LIGA	241	259
\N	1	7	3	1	4	\N	\N	LIGA	390	110
\N	1	8	3	1	5	\N	\N	LIGA	275	225
\N	6	9	3	1	6	\N	\N	LIGA	198	302
\N	2	10	3	2	3	\N	\N	LIGA	333	167
\N	4	11	3	2	4	\N	\N	LIGA	210	290
\N	2	12	3	2	5	\N	\N	LIGA	265	235
\N	6	13	3	2	6	\N	\N	LIGA	150	350
\N	3	14	3	3	4	\N	\N	LIGA	284	216
\N	5	15	3	3	5	\N	\N	LIGA	199	301
\N	3	16	3	3	6	\N	\N	LIGA	320	180
\N	4	17	3	4	5	\N	\N	LIGA	260	240
\N	4	18	3	4	6	\N	\N	LIGA	305	195
\N	5	19	3	5	6	\N	\N	LIGA	278	222
\N	1	20	3	1	5	\N	\N	PLAYOFFS	287	213
\N	4	21	3	3	4	\N	\N	PLAYOFFS	196	304
\N	1	22	3	1	4	\N	\N	PLAYOFFS	341	159
\N	1	99	10	1	6	\N	\N	\N	4	3
\N	2	76	8	1	2	\N	\N	LIGA	150	200
\N	1	77	8	1	3	\N	\N	LIGA	320	280
\N	1	78	8	1	4	\N	\N	LIGA	390	110
\N	1	79	8	1	5	\N	\N	LIGA	275	225
\N	6	80	8	1	6	\N	\N	LIGA	198	302
\N	2	81	8	2	3	\N	\N	LIGA	333	167
\N	4	82	8	2	4	\N	\N	LIGA	210	290
\N	2	83	8	2	5	\N	\N	LIGA	265	235
\N	6	84	8	2	6	\N	\N	LIGA	150	350
\N	3	85	8	3	4	\N	\N	LIGA	284	216
\N	5	86	8	3	5	\N	\N	LIGA	199	301
\N	3	87	8	3	6	\N	\N	LIGA	320	180
\N	4	88	8	4	5	\N	\N	LIGA	260	240
\N	4	89	8	4	6	\N	\N	LIGA	305	195
\N	5	90	8	5	6	\N	\N	LIGA	278	222
\N	1	91	8	1	5	\N	\N	PLAYOFFS	287	213
\N	4	92	8	2	4	\N	\N	PLAYOFFS	196	304
\N	5	94	8	2	5	\N	\N	TERCER_LUGAR	228	272
\N	1	93	8	1	4	\N	\N	FINAL	341	159
1	4	95	10	7	4	\N	10	\N	1	3
1	6	96	10	6	5	\N	10	\N	2	0
1	2	97	10	8	2	\N	10	\N	2	4
1	1	98	10	1	3	\N	10	\N	5	1
\N	2	100	10	2	4	\N	\N	\N	5	0
\N	4	102	10	4	6	\N	\N	TERCER_LUGAR	3	2
\N	1	101	10	2	1	\N	\N	FINAL	1	2
1	1	1	1	1	2	\N	1	\N	2	1
\N	\N	103	1	1	\N	\N	\N	\N	\N	\N
\.


--
-- TOC entry 5034 (class 0 OID 16471)
-- Dependencies: 223
-- Data for Name: torneo_participante; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.torneo_participante (participante_id, torneo_id) FROM stdin;
1	1
2	1
1	8
2	8
3	8
4	8
5	8
6	8
1	3
2	3
3	3
4	3
5	3
6	3
7	10
4	10
6	10
5	10
8	10
2	10
1	10
3	10
\.


--
-- TOC entry 5036 (class 0 OID 16477)
-- Dependencies: 225
-- Data for Name: torneos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.torneos (id, estado, juego, nombre) FROM stdin;
1	EN_CURSO	Dream League Soccer	Liga ITLA
3	FINALIZADO	MarioKart	Atlas League
8	FINALIZADO	MarioKart	Mk League
10	FINALIZADO	OnevsOne	Copa Prueba
\.


--
-- TOC entry 5044 (class 0 OID 0)
-- Dependencies: 219
-- Name: participantes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.participantes_id_seq', 8, true);


--
-- TOC entry 5045 (class 0 OID 0)
-- Dependencies: 221
-- Name: partidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.partidos_id_seq', 103, true);


--
-- TOC entry 5046 (class 0 OID 0)
-- Dependencies: 224
-- Name: torneos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.torneos_id_seq', 10, true);


--
-- TOC entry 4871 (class 2606 OID 16463)
-- Name: participantes participantes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participantes
    ADD CONSTRAINT participantes_pkey PRIMARY KEY (id);


--
-- TOC entry 4873 (class 2606 OID 16470)
-- Name: partidos partidos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidos
    ADD CONSTRAINT partidos_pkey PRIMARY KEY (id);


--
-- TOC entry 4875 (class 2606 OID 16484)
-- Name: torneos torneos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneos
    ADD CONSTRAINT torneos_pkey PRIMARY KEY (id);


--
-- TOC entry 4881 (class 2606 OID 16515)
-- Name: torneo_participante fk2qlcfadtj7p944ij8kultdxfm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneo_participante
    ADD CONSTRAINT fk2qlcfadtj7p944ij8kultdxfm FOREIGN KEY (torneo_id) REFERENCES public.torneos(id);


--
-- TOC entry 4876 (class 2606 OID 16505)
-- Name: partidos fk5jbh7itc364qxrmbwni3mdauv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidos
    ADD CONSTRAINT fk5jbh7itc364qxrmbwni3mdauv FOREIGN KEY (torneo_id) REFERENCES public.torneos(id);


--
-- TOC entry 4877 (class 2606 OID 16495)
-- Name: partidos fk6eueul3vgnmlr43g09ilakvfw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidos
    ADD CONSTRAINT fk6eueul3vgnmlr43g09ilakvfw FOREIGN KEY (jugador2_id) REFERENCES public.participantes(id);


--
-- TOC entry 4878 (class 2606 OID 16490)
-- Name: partidos fk6lyvm7jbtm15fbwfcvbnjq2v6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidos
    ADD CONSTRAINT fk6lyvm7jbtm15fbwfcvbnjq2v6 FOREIGN KEY (jugador1_id) REFERENCES public.participantes(id);


--
-- TOC entry 4879 (class 2606 OID 16500)
-- Name: partidos fk9wx8lecf1y1qyeqru72hcaeoy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidos
    ADD CONSTRAINT fk9wx8lecf1y1qyeqru72hcaeoy FOREIGN KEY (siguiente_partido_id) REFERENCES public.partidos(id);


--
-- TOC entry 4882 (class 2606 OID 16510)
-- Name: torneo_participante fkatlrjperyo8fw15f39h5vlsaf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneo_participante
    ADD CONSTRAINT fkatlrjperyo8fw15f39h5vlsaf FOREIGN KEY (participante_id) REFERENCES public.participantes(id);


--
-- TOC entry 4880 (class 2606 OID 16485)
-- Name: partidos fksl8n38wgwb2noxqwo8frlm7fl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidos
    ADD CONSTRAINT fksl8n38wgwb2noxqwo8frlm7fl FOREIGN KEY (ganador_id) REFERENCES public.participantes(id);


--
-- TOC entry 5043 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


-- Completed on 2026-04-15 23:07:14

--
-- PostgreSQL database dump complete
--

\unrestrict Cs7LmYAjeD5xKkSjiLOMExHYTyIzL6XuQ5Ie2RbT3vcShFD7j3IgcqGYvQQ712k

