spring.application.name=gestor-torneo
# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/torneos_db
spring.datasource.username=postgres
spring.datasource.password=022517

# Configuracion de Hibernate (El traductor de Java a SQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true